// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://copuoksaimxydtagsutp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvcHVva3NhaW14eWR0YWdzdXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzg5NzcsImV4cCI6MjA3MDY1NDk3N30.erXKpQjIXfCQO8tixpRVKlVvZ-LEe6Pi7TDWjNKJQRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});